[build]
  command = "echo 'No build command needed for static HTML'"
  publish = "."
  functions = "netlify/functions"

[dev]
  command = "echo 'Starting development server'"
  port = 8888
  publish = "."
  autoLaunch = true

# Usar la página de redirección como página principal
[[redirects]]
  from = "/"
  to = "/netlify-redirect.html"
  status = 200

# Redireccionar todas las demás solicitudes a la versión principal
[[redirects]]
  from = "/*"
  to = "https://smartvision-app.onrender.com/:splat"
  status = 302
  force = true
