[build]
  command = "echo 'No build command needed for static HTML'"
  publish = "."
  functions = "netlify/functions"

[dev]
  command = "echo 'Starting development server'"
  port = 8888
  publish = "."
  autoLaunch = true

[[redirects]]
  from = "/extract-text"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/check-init"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/.netlify/functions/auth/login"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/.netlify/functions/auth/verify"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
