[build]
  command = "npm install"
  publish = "templates"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 8888
  publish = "templates"
  autoLaunch = true

[[redirects]]
  from = "/extract-text"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
