[build]
  command = "echo 'No build command needed for static HTML'"
  publish = "."
  functions = "netlify/functions"

[dev]
  command = "echo 'Starting development server'"
  port = 8888
  publish = "."
  autoLaunch = true

# Servir el archivo index.html de la raíz
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Redireccionar las llamadas a la API a las funciones de Netlify
[[redirects]]
  from = "/extract-text"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/check-init"
  to = "/.netlify/functions/api"
  status = 200

# Para cualquier otra ruta, servir index.html (para SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
